ci(pypi): set trusted publisher on TEST pypi

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -69,7 +69,7 @@ jobs:
     permissions:
       contents: write
     steps:
-      - name: Download All Artifacts and Merge
+      - name: Download all builds and merge
         uses: actions/download-artifact@v4
         with:
           path: ./release-assets
@@ -88,7 +88,12 @@ jobs:
 
       - name: Get project release version
         id: release_version
-        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
+        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
+
+      - name: Fail if version doesn't match pattern (e.g., v1.2.3, 1.2.3, 1.2.3-alpha.1)
+        run: |
+          echo "Version: ${{ steps.release_version.outputs.VERSION }}"
+          [[ "${{ steps.release_version.outputs.VERSION }}" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(\.[a-z0-9]+)?$ ]] || exit 1
 
       - name: Set up Python to install this project
         uses: actions/setup-python@v5
@@ -108,11 +113,15 @@ jobs:
       - name: Show Release notes
         run: cat RELEASE_NOTES.md
 
-      - name: Create GitHub release (upload release-assets and release notes)
+      - name: Check if all assets are ready
         run: |
+          set -e  # Kill the release if any of the following commands fail
           echo "Creating GitHub release for version ${{ steps.release_version.outputs.VERSION }}"
           echo "Appending release notes: $(cat RELEASE_NOTES.md)"
-          echo "Uploading release-assets: $(ls -la ./release-assets)"
+          cat cat RELEASE_NOTES.md)
+          echo "Uploading release-assets: "
+          ls -la release-assets/*.whl
+          ls -la release-assets/*.tar.gz
 
       # - name: Create GitHub release (and upload assets)
       #   id: create_release
@@ -133,6 +142,7 @@ jobs:
     runs-on: ubuntu-latest
     permissions:
       contents: write
+      id-token: write # For trusted publishing
     steps:
       - name: Download all builds and merge
         uses: actions/download-artifact@v4
@@ -145,14 +155,14 @@ jobs:
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
           repository-url: https://test.pypi.org/legacy/
-          password: ${{ secrets.TEST_PYPI_PROJECT_TOKEN }}
+          # password: ${{ secrets.TEST_PYPI_PROJECT_TOKEN }}  #  Don't need if trusted publishing set on PyPI
           packages-dir: release-assets/
-          # skip-existing: true
           verify-metadata: true # 'twine check' before upload
+          skip-existing: true
 
-      # - name: Publish to PyPI
-      #   uses: pypa/gh-action-pypi-publish@release/v1
-      #   with:
-      #     password: ${{ secrets.PYPI_PROJECT_TOKEN }}
-      #     packages-dir: release-assets/
-      #     verify-metadata: true # 'twine check' before upload
+      - name: Publish to PyPI
+        uses: pypa/gh-action-pypi-publish@release/v1
+        with:
+          # password: ${{ secrets.PYPI_PROJECT_TOKEN }}   #  Don't need if trusted publishing set on PyPI
+          packages-dir: release-assets/
+          verify-metadata: true # 'twine check' before upload
